### ISSUE TITLE
[CreuSAT] restart heuristic

### ISSUE THREAD

**Issue by m-fleury** [sarsko/CreuSAT#38]
Is it expected that the fast and slow heuristic have the same initial value in CreuSAT?

```
    pub fn new(f: &Formula) -> Solver {
        Solver {
            num_lemmas: 0,
            max_lemmas: 2000,
            num_conflicts: 0,
            initial_len: f.clauses.len(),
            inc_reduce_db: 300,
            fast: 16777216, // 1 << 24
            slow: 16777216, // 1 << 24
            perm_diff: vec::from_elem(0, f.num_vars),
        }
    }
```

That seems odd (and a good way to never restart actually).

**Comment by sarsko** [comment]
Hiya,

I believe having the same value is expected. How would you have done it?

The current scheme follows MicroSat: https://github.com/marijnheule/microsat/blob/master/microsat.c#L190, https://github.com/marijnheule/microsat/blob/master/microsat.c#L123-L124, https://github.com/marijnheule/microsat/blob/master/microsat.c#L168-L171

It flows like so:
- Init: https://github.com/sarsko/CreuSAT/blob/master/CreuSAT/src/solver.rs#L75-L87
- Update: https://github.com/sarsko/CreuSAT/blob/master/CreuSAT/src/solver.rs#L127-L128 and https://github.com/sarsko/CreuSAT/blob/master/CreuSAT/src/util.rs#L38-L56
- Restart on fast > slow * 1.25: https://github.com/sarsko/CreuSAT/blob/master/CreuSAT/src/solver.rs#L284-L291

**Comment by m-fleury** [comment]
ah sorry, I got confused between the initial value and the coefficient. 

Sorry for the noise!
