### ISSUE TITLE
Default Citation

### ISSUE THREAD

**Issue by m-fleury** [sarsko/CreuSAT#40]
Could you add what should be cited in the readme? Here is the bibtex entry I currently use, but it might not be optimal:

```
@mastersthesis{creusat,
  author       = {Skotåm, Sarek Høverstad},
  title	       = {{CreuSAT}, Using {Rust} and {Creusot} to create the
                  world’s fastest deductively verified {SAT} solver},
  school       = {University of Oslo},
  year	       = {2022},
  url	       =
                  {https://www.duo.uio.no/handle/10852/96757},
}
```

Thank you very much

**Comment by sarsko** [comment]
Thanks!

Updated the README with information on how to cite. It is the same as yours after being put into Zotero and then exported, so it should be fine to keep using the one you have been using.
