### ISSUE TITLE
Panic at CreuSAT/src/parser.rs:130:14 on simple formula

### ISSUE THREAD

**Issue by wintered** [sarsko/CreuSAT#44]
[b36aacd](https://github.com/sarsko/CreuSAT/commit/b36aacd53874c49e77493ac6ecceabf0b1968154)

```
$./CreuSAT --file f.cnf                                                            
c Reading file 'f.cnf'                                                             
c Parsed formula with 1 clauses and 1 literals                                     
thread 'main' panicked at CreuSAT/src/parser.rs:130:14:                            
Sarek should really make the parser non-binary                                     
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace   
$minisat f.cnf|tail -n 1                                                           
SATISFIABLE                                                                        
$cat f.cnf                                                                         
cnf 1 1                                                                            
-1 1 0                                                                            
```

**Comment by sarsko** [comment]
Hi, thank you. 

This does not look like a valid cnf formula to me — there is no `p` line. I believe it should work if `cnf 1 1` is substituted with `p cnf 1 1`

**Comment by sarsko** [comment]
Oh, indeed, I didn't pay attention to the error line. Looks like the first formula is also accepted by the parser.

Hmm, yes, I now remember. I added invariant establishing with a mix of needed invariants and convenient invariants, but never bothered to add and prove "formula fixing" (eg for this case remove the clause, for duplicated literals reduce the clause to only contain one literal) for the convenient ones. The idea was to at some point go and implement a better "mid-layer" with that + some actual preprocessing stuff, but well, I never got around to it.

Dunno where that leaves this issue. Thanks, and sorry. I'd like to improve this, but not sure I will anytime soon.

**Comment by wintered** [comment]
@sarsko I'll close this now. Feel free to reopen, should it become relevant.
